# This is a basic workflow to help you get started with Actions

name: CUDA-Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-cuda
    steps:
    - name: Check builder for CUDA
      run: |
        (nvcc --version) || echo 'please install cuda'
        # Get-Item 'c:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include\cudnn.h' || echo 'install cudnn as described in the readme.md'
        echo "CUDA_HOME=c:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7" >> $GITHUB_ENV
        echo "CUDA_PATH=c:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin" >> $GITHUB_ENV
    - name: Check environment
      run: |
        echo CUDA_HOME=${{env.CUDA_HOME}}
        echo CUDA_PATH=${{env.CUDA_PATH}}
